[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/*"  # Apply to all routes
  [headers.values]
    Access-Control-Allow-Origin = "https://cooptexepf.netlify.app"
    
[build]
  functions = "functions"

[dev]
  publish = "build"
