[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/"
  [headers.values]
    Access-Control-Allow-Origin = "*"
  
[build]
      functions = "functions"

[dev]
   publish = "build"
